### ISSUE TITLE
List places API returns an error

### ISSUE THREAD

**Issue by vivienchevallier** [microsoftgraph/msgraph-sdk-serviceissues#49]
Listing places is currently returning an error with the version 0.8.0 of the SDK.
```
var graphServiceClient = new GraphServiceClient(authenticationProvider);
var places = await graphServiceClient.Places.Request().GetAsync();
```

When looking at the [documentation](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&tabs=http#example-1-list-all-the-rooms-defined-in-the-tenant) the endpoint to call to **_list all the rooms defined in the tenant_** is:
`https://graph.microsoft.com/beta/places/microsoft.graph.room`
After testing with Postman the endpoint is working as expected.

However when using the SDK and after looking at the code, the generated GraphServiceClient in the SDK is calling:
`https://graph.microsoft.com/beta/places`

As a temporary solution I'm currently instantiating the request builder for places like the following:
`new GraphServicePlacesCollectionRequestBuilder(graphServiceClient.BaseUrl + "/places/microsoft.graph.room", graphServiceClient);` 
[AB#7152](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7152)

**Comment by petrhollayms** [comment]
Thank you for reporting this issue. This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph 

For now, we will close the issue on our side but feel free to open it in the relevant repository if you think the issue is specific to SDK. 
Please let us know if this helps! 

Note: We will close this repository on April 19, 2024.
